# Generated by Django 6.0.7 on 2026-09-16 23:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0042_org_bop_organization_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BopEventLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_id', models.CharField(help_text='Unique event UUID sent by the Bop source application', max_length=255, verbose_name='Event ID')),
                ('source_app', models.CharField(help_text="Origin app (e.g., 'bop_clients', 'bop_chatbot')", max_length=64, verbose_name='Source Application')),
                ('event_type', models.CharField(help_text="Domain event name (e.g., 'prospect.ready_for_crm')", max_length=128, verbose_name='Event Type')),
                ('external_entity_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='External Entity ID')),
                ('idempotency_key', models.CharField(blank=True, help_text='Unique key for deduplication across retries', max_length=255, null=True, verbose_name='Idempotency Key')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Full event JSON payload')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=32, verbose_name='Status')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Bop Event Log',
                'verbose_name_plural': 'Bop Event Logs',
                'db_table': 'bop_event_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='bop_event_l_org_id_7db03d_idx'), models.Index(fields=['org', 'status'], name='bop_evt_status_idx'), models.Index(fields=['org', 'source_app', 'event_type'], name='bop_evt_src_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'event_id'), name='unique_bop_event_id_per_org'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('org', 'idempotency_key'), name='unique_bop_event_idempotency_per_org')],
            },
        ),
        migrations.CreateModel(
            name='ExternalEntityMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_app', models.CharField(help_text="Identifier of the source system (e.g., 'bop_clients', 'bop_erp', 'bop_social')", max_length=64, verbose_name='Source Application')),
                ('external_entity_type', models.CharField(help_text="Type of the entity in the source system (e.g., 'prospect', 'customer')", max_length=64, verbose_name='External Entity Type')),
                ('external_entity_id', models.CharField(help_text='Primary identifier of the entity in the source system', max_length=255, verbose_name='External Entity ID')),
                ('idempotency_key', models.CharField(blank=True, help_text='Optional unique key to ensure idempotent creation per organization', max_length=255, null=True, verbose_name='Idempotency Key')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'External Entity Map',
                'verbose_name_plural': 'External Entity Maps',
                'db_table': 'external_entity_map',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='external_en_org_id_2ad76d_idx'), models.Index(fields=['org', 'source_app', 'external_entity_type', 'external_entity_id'], name='ext_map_lookup_idx'), models.Index(fields=['content_type', 'object_id'], name='ext_map_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'source_app', 'external_entity_type', 'external_entity_id'), name='unique_external_entity_map_per_org'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('org', 'idempotency_key'), name='unique_external_entity_idempotency_per_org')],
            },
        ),
    ]
