# Generated by Django 6.0.7 on 2026-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bop_integration', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='bopeventlog',
            name='causation_id',
            field=models.CharField(blank=True, help_text='Direct causal event identifier', max_length=255, null=True, verbose_name='Causation ID'),
        ),
        migrations.AddField(
            model_name='bopeventlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Cross-application correlation identifier', max_length=255, null=True, verbose_name='Correlation ID'),
        ),
        migrations.AddField(
            model_name='bopeventlog',
            name='event_version',
            field=models.PositiveIntegerField(default=1, help_text='Canonical schema version of the event', verbose_name='Event Version'),
        ),
        migrations.AddField(
            model_name='bopeventlog',
            name='external_entity_type',
            field=models.CharField(blank=True, help_text="Domain entity type in source application (e.g. 'prospect')", max_length=64, null=True, verbose_name='External Entity Type'),
        ),
        migrations.AddField(
            model_name='bopeventlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Contextual event metadata dictionary'),
        ),
    ]
