# Generated by Django 6.0.7 on 2026-09-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_clear_stale_rls_force_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='bop_organization_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Global Bop Universe Organization UUID', null=True, unique=True),
        ),
    ]
