# Generated by Django 6.0.7 on 2026-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_org_bop_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccesstoken',
            name='source_app',
            field=models.CharField(blank=True, choices=[('bop_assistant', 'bop_assistant'), ('bop_chatbot', 'bop_chatbot'), ('bop_clients', 'bop_clients'), ('bop_erp', 'bop_erp'), ('bop_social', 'bop_social')], db_index=True, help_text='Authenticated Bop Universe source application identity bound to this token', max_length=64, null=True),
        ),
    ]
