# Generated by Django 6.0.7 on 2026-09-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_sample'),
        ('leads', '0016_alter_leadpipeline_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Related company account (optional before or after lead conversion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.account'),
        ),
    ]
